name: Deploy DMT on SKALE

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Compile
        run: npx hardhat compile

      - name: Deploy to SKALE
        env:
          SKALE_RPC_URL: ${{ secrets.SKALE_RPC_URL }}
          SKALE_CHAIN_ID: ${{ secrets.SKALE_CHAIN_ID }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
        run: npx hardhat run scripts/deploy.js --network skale
