name: Deploy DMT on SKALE

on:
  workflow_dispatch:   # 👈 This makes the manual "Run workflow" button appear

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy to SKALE
        run: node scripts/deploy-dmt.js
        env:
          SKALE_RPC_URL: ${{ secrets.SKALE_RPC_URL }}
          SKALE_CHAIN_ID: ${{ secrets.SKALE_CHAIN_ID }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
